PUT http://localhost:5000/books/1
Content-Type: application/json

{
  "id": 1,
  "title": "Head First JavaScript programming",
  "authors":"Elisabeth Robson, Eric Freeman",
  "publicationDate": "may 6, 2014",
}